import type { AppSettings } from "../types";

export const transcriptionModels: Record<
  AppSettings["transcriptionProvider"],
  Array<{
    value: string;
    label: string;
    languages: string[];
  }>
> = {
  deepgram: [
    {
      value: "nova-3",
      label: "Nova-3",
      languages: [
        "multi",
        "ar",
        "ar-AE",
        "ar-SA",
        "ar-QA",
        "ar-KW",
        "ar-SY",
        "ar-LB",
        "ar-PS",
        "ar-JO",
        "ar-EG",
        "ar-SD",
        "ar-TD",
        "ar-MA",
        "ar-DZ",
        "ar-TN",
        "ar-IQ",
        "ar-IR",
        "be",
        "bn",
        "bs",
        "bg",
        "ca",
        "zh-HK",
        "zh",
        "zh-CN",
        "zh-Hans",
        "zh-TW",
        "zh-Hant",
        "hr",
        "cs",
        "da",
        "da-DK",
        "nl",
        "nl-BE",
        "en",
        "en-US",
        "en-AU",
        "en-GB",
        "en-IN",
        "en-NZ",
        "et",
        "fi",
        "fr",
        "fr-CA",
        "de",
        "de-CH",
        "el",
        "gu",
        "gu-IN",
        "he",
        "hi",
        "hu",
        "id",
        "it",
        "ja",
        "kn",
        "ko",
        "ko-KR",
        "lv",
        "lt",
        "mk",
        "ms",
        "mr",
        "no",
        "fa",
        "pl",
        "pt",
        "pt-BR",
        "pt-PT",
        "ro",
        "ru",
        "sr",
        "sk",
        "sl",
        "es",
        "es-419",
        "sv",
        "sv-SE",
        "tl",
        "ta",
        "te",
        "th",
        "th-TH",
        "tr",
        "uk",
        "ur",
        "vi",
      ],
    },
    {
      value: "nova-3-medical",
      label: "Nova-3 Medical",
      languages: [
        "en",
        "en-US",
        "en-AU",
        "en-CA",
        "en-GB",
        "en-IE",
        "en-IN",
        "en-NZ",
      ],
    },
    {
      value: "nova-2",
      label: "Nova-2",
      languages: [
        "multi",
        "bg",
        "ca",
        "zh",
        "zh-CN",
        "zh-Hans",
        "zh-TW",
        "zh-Hant",
        "zh-HK",
        "cs",
        "da",
        "da-DK",
        "nl",
        "nl-BE",
        "en",
        "en-US",
        "en-AU",
        "en-GB",
        "en-NZ",
        "en-IN",
        "et",
        "fi",
        "fr",
        "fr-CA",
        "de",
        "de-CH",
        "el",
        "hi",
        "hu",
        "id",
        "it",
        "ja",
        "ko",
        "ko-KR",
        "lv",
        "lt",
        "ms",
        "no",
        "pl",
        "pt",
        "pt-BR",
        "pt-PT",
        "ro",
        "ru",
        "sk",
        "es",
        "es-419",
        "sv",
        "sv-SE",
        "th",
        "th-TH",
        "tr",
        "uk",
        "vi",
      ],
    },
    {
      value: "nova-2-conversationalai",
      label: "Nova-2 Conversational AI",
      languages: ["en", "en-US"],
    },
    {
      value: "nova-2-medical",
      label: "Nova-2 Medical",
      languages: ["en", "en-US"],
    },
    {
      value: "nova-2-phonecall",
      label: "Nova-2 Phone Call",
      languages: ["en", "en-US"],
    },
  ],
  assemblyAi: [
    {
      value: "u3-rt-pro",
      label: "Universal-3 Pro Streaming",
      languages: ["multi", "en", "es", "fr", "de", "it", "pt"],
    },
    {
      value: "universal-streaming-english",
      label: "Universal Streaming English",
      languages: ["en"],
    },
    {
      value: "universal-streaming-multilingual",
      label: "Universal Streaming Multilingual",
      languages: ["multi"],
    },
    {
      value: "whisper-rt",
      label: "Whisper Streaming",
      languages: ["multi"],
    },
  ],
};
